Added italian translations
canonical/ubuntu-desktop-installer pull request #10
Opened 2021-02-02 18:27 UTC by GioPan04

Hi,
I added the translations for Italian language.

2021-02-02 21:13 UTC, oSoMoN requested changes
This looks good to me (I can't really speak Italian though, so I'm not reviewing the correctness of the translations), thanks for these!

See a couple of minor suggestions inline.

Note that for testing purposes, I had to add an entry for Italian to `subiquity_client/subiquity/languagelist`.

2021-02-02 21:13 UTC, oSoMoN commented on ubuntu_desktop_installer/lib/l10n/messages_it.dart
> +  static m1(url) => "Forse vorresti leggere le <a href=\"${url}\">informazioni di rilascio</a>.";
`m0` and `m1` are missing an explicit return type (`String`), see e.g. messages_fr.dart. This is [a bug in dart itself](https://github.com/dart-lang/intl_translation/issues/99), for now you will have to manually add them.

2021-02-02 21:13 UTC, oSoMoN commented on ubuntu_desktop_installer/lib/l10n/intl_it.arb
> +  "You can try Ubuntu without making any changes to your computer.": "Puoi provare Ubuntu senza apportare alcuna modifica al tuo computer",
There should probably be a full stop at the end of the sentence, for consistency.

2021-02-02 21:13 UTC, oSoMoN commented on ubuntu_desktop_installer/lib/l10n/intl_it.arb
> +  "Repairing will reinstall all installed software without touching documents or settings.": "La riparazione reinstallerá tutti i programmi senza toccare alcun documento o impostazione",
There should probably be a full stop at the end of the sentence, for consistency.

2021-02-02 22:03 UTC, GioPan04 commented
Okay done, i push a commit

2021-02-02 22:31 UTC, FedericoAntoniazzi commented
I speak italian and translations made by @GioPan04 are perfect. Lgtm

2021-02-12 19:05 UTC, merged

2021-02-12 19:06 UTC, oSoMoN commented
Thanks @GioPan04 and @FedericoAntoniazzi, this is now merged.