Dynamically built and localized installation slides
canonical/ubuntu-desktop-installer pull request #568
Opened 2021-12-13 14:48 UTC by jpnurmi

The old slides were images. The new slides are built with Flutter widgets.

https://user-images.githubusercontent.com/140617/145833452-ab51e36f-df77-4dba-a556-9914e8e6dc91.mp4

Ref: #42

2021-12-14 10:15 UTC, jpnurmi commented
Test coverage reduces quite a bit. The slide "framework" should have some tests.

2022-01-05 12:22 UTC, jpnurmi commented
I've again split off the flavor translations to a separate PR #592 because now that I think of it, it would be nicer to not mix the generic non-installer-specific flavor classes with these installer-specific installation slides.

2022-01-07 10:08 UTC, jpnurmi commented
- this depends on PR #592
- to make reviewing easier, commits marked with "[SQUASHED]" are only adding strings and assets and regenerating localizations
- the last commit is the important part of this PR

2022-01-19 16:39 UTC, jpnurmi commented
A quick prototype with assets stolen from ubiquity-slideshow-ubuntu

![Screenshot from 2022-01-19 17-35-14](https://user-images.githubusercontent.com/140617/150174671-24fb5599-053e-48b9-92c4-5df13d7c5e8d.png)

2022-02-01 14:03 UTC, oSoMoN requested changes
This looks good to me overall, just a bunch of minor comments/suggestions.

The screenshots in the slides all look blurry to my untrained eye, but they appear to be [the original screenshots](https://git.launchpad.net/ubuntu/+source/ubiquity-slideshow-ubuntu/tree/slideshows/ubuntu/slides/screenshots) from ubiquity-slideshow-ubuntu, so that's not a regression, and it should be addressed there.

And one suggestion: could the left/right arrow keys trigger navigation through the slides?

2022-02-02 07:20 UTC, jpnurmi commented
> And one suggestion: could the left/right arrow keys trigger navigation through the slides?

Wait a sec, now that I read this again, I misunderstood and made it wrap.

2022-02-02 07:22 UTC, jpnurmi commented
> And one suggestion: could the left/right arrow keys trigger navigation through the slides?

Sounds good. Let's do this in the `SlideShow` widget in `ubuntu-flutter-plugins`.

2022-02-02 08:32 UTC, jpnurmi commented
Arrow keys for SlideShow: https://github.com/canonical/ubuntu-flutter-plugins/pull/30

2022-02-02 10:10 UTC, oSoMoN commented on packages/ubuntu_desktop_installer/lib/slides/default_slides.dart
> +            context.lang.supportSlideDocumentation(context.flavor.name),
Can we add the missing hyperlinks on the last slide (support), like in [the original ubiquity slideshow](https://git.launchpad.net/ubuntu/+source/ubiquity-slideshow-ubuntu/tree/slideshows/ubuntu/slides/gethelp.html) ?

2022-02-02 11:33 UTC, jpnurmi commented
I knew I would one day commit the default route change. :man_facepalming:

2022-02-02 11:51 UTC, jpnurmi commented
The snap build failure looks like a temporary hiccup:
```
Err:3 http://archive.ubuntu.com/ubuntu focal/main amd64 libfuse2 amd64 2.9.9-3
  Could not connect to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (91.189.88.142), connection timed out
```

2022-02-02 11:53 UTC, oSoMoN approved these changes
LGTM now, let's merge!

2022-02-02 11:56 UTC, merged