Migrate Subiquity client to null-safety
canonical/ubuntu-desktop-installer pull request #73
Opened 2021-04-23 22:31 UTC by jpnurmi

2021-04-24 08:45 UTC, jpnurmi commented
Hey, I've been struggling a bit with dependencies, particularly in `ubuntu_desktop_installer`. I wanted to use [pattern matching](https://pub.dev/packages/freezed#unionssealed-classes) for #30, but there's a tricky conflict with the current dependencies :

```
Bad state: Unexpected diagnostics:
/home/jpnurmi/.fvm/versions/dev/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:166:25 - This requires the 'non-nullable' language feature to be enabled.
/home/jpnurmi/.fvm/versions/dev/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:30:49 - This requires the 'non-nullable' language feature to be enabled.
/home/jpnurmi/.fvm/versions/dev/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:390:19 - This requires the 'non-nullable' language feature to be enabled.
[...]
```

Migrating to null-safety would help to upgrade all dependencies to the latest versions, which would solve the conflict too. I have already verified that migrating `ubuntu_desktop_installer` is no problem once `subiquity_client` has been migrated.

2021-04-26 15:35 UTC, oSoMoN requested changes
Would you mind extracting [this commit](682b267b47e04d1879ecfac74a7468f193c759ba) into a separate PR?

2021-04-26 15:40 UTC, jpnurmi commented
Done: https://github.com/canonical/ubuntu-desktop-installer/pull/74. Should've done it in the first place but I was lazy. :)

2021-04-26 17:34 UTC, jpnurmi commented on packages/subiquity_client/pubspec.yaml
> +  test: ^1.17.0
Sorry for the re-ordering here. I'm using the Pubspec Assistant VS Code extension for managing dependencies. It likes to keep these in alphabetical order - I hope that's ok...

2021-04-26 17:36 UTC, jpnurmi commented on packages/subiquity_client/pubspec.yaml
> +  sdk: '>=2.12.0 <3.0.0'
(not that it matters much, but the migration tool prefers single quotes)

2021-04-26 20:37 UTC, oSoMoN commented
LGTM, thanks!

2021-04-26 20:37 UTC, merged