Add issue templates
canonical/ubuntu-desktop-installer pull request #760
Opened 2022-03-29 11:04 UTC by jpnurmi

2022-03-29 11:06 UTC, jpnurmi commented
![Screenshot from 2022-03-29 13-04-43](https://user-images.githubusercontent.com/140617/160598167-519ace6d-dc07-4098-ac0f-5de527bd3d6f.png)
![Screenshot from 2022-03-29 13-05-03](https://user-images.githubusercontent.com/140617/160598170-70ce191c-ff49-4b95-b7cc-7d66af3c1800.png)
![Screenshot from 2022-03-29 13-05-18](https://user-images.githubusercontent.com/140617/160598172-88b2e19b-c9be-47f3-a1fd-daaecc28f1b5.png)

2022-03-29 14:08 UTC, jpnurmi commented
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

2022-03-29 17:12 UTC, jpnurmi commented
# New issue
![image](https://user-images.githubusercontent.com/140617/160667777-f030e057-a32f-4e04-8f0b-151ff1367864.png)

# Bug report
![image](https://user-images.githubusercontent.com/140617/160667863-43117f6d-b828-4988-9695-e450bc61156a.png)

# Feature request
![image](https://user-images.githubusercontent.com/140617/160667935-6ab957a7-32a7-41c5-a31f-597410b73ce7.png)

2022-10-03 11:02 UTC, seb128 requested changes
Thanks for working on this and sorry for not picking it up earlier. It seems fine to me, I'm unsure if we should start by asking the version of Ubuntu/the ISO but that probably doesn't matter as long as we are rolling and we don't have different series available.

I've one small tweak request and then let's merge.

2022-10-07 08:28 UTC, jpnurmi commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +    placeholder: |
What about proposing a command that collects all relevant logs?

2023-03-17 12:13 UTC, seb128 commented
I think we could land the current version and iterate later if there are improvements we want to do

2023-08-31 13:42 UTC, merged